---
- name: Enable internet services
  hosts: all
  become: True
  tasks:
    - name: latest version of all required packages
      yum:
        name:
          - firewalld
	  - httpd
	  - mariadb-server
	  - php
	  - php-mysqlnd
	state: latest 

    - name: firewalld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started

    - name: mariadb enabled and running
      service:
        name: mariadb
        enabled: true  
        state: started 	
    - name: test page is installed
      copy:
        content: "This is the internet"
        dest: /var/www/html/index.html